server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: habargde
    url: jdbc:postgresql://localhost:5432/diploma
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true


